# Generated by Django 4.2.1 on 2024-07-08 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
