# Generated by Django 5.0.6 on 2024-07-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
